Name=input("Enter your name:")
Age=int(input("Enter your age:"))
Department=input("Enter your department")
College=input("Enter your college:")
Email=input("Enter your email")
s1=int(input("Enter DSA mark:"))
s2=int(input("Enter FDSA mark:"))
s3=int(input("Enter Maths mark:"))
s4=int(input("Enter OOPS mark:"))
s5=int(input("Enter AI mark:"))
print("________StTUDENT RESULT CARD___________")
print("Name:",Name)
print("Age:",Age)
print("Department:",Department)
print("College:",College)
print("Email:",Email)
total=s1+s2+s3+s4+s5
print(f"CGPA {(total)/5}")
